version: '1'
services:
  minio:
    hostname: minio-server
    image: 'minio/minio:latest'
    container_name: minio-server
    command: server --console-address ":9001" /minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    volumes:
      - '~/minio/data:/minio'
  hadoop:
    hostname: hadoop-master
    image: 'prestodb/hive3.1-hive:10'
    container_name: hadoop-master
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    volumes:
      - './hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml'
    ports:
    - '9083:9083'
    depends_on:
      - minio
  presto:
    hostname: presto
    image: 'ahanaio/prestodb-sandbox:0.280'
    container_name: presto
    ports:
      - '8080:8080'
    volumes:
      - './presto/etc/catalog/minio.properties:/opt/presto-server/etc/catalog/minio.properties'
    depends_on:
      - minio
      - hadoop
  mc-job:
    image: 'minio/mc:latest'
    environment:
      MC_HOST_presto: "http://minioadmin:minioadmin@172.19.0.2:9000"
    volumes:
      - './minio/data:/minio'
    depends_on:
      - minio
      - hadoop
    entrypoint: |
      /bin/bash -c "
      /usr/bin/mc mb presto/customer-data-text;
      /usr/bin/mc mb presto/customer-data-orc;
      /usr/bin/mc mirror minio/customer-data-text presto/customer-data-text;
      "
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.19.0.1/16
